### PR TITLE
[WIP] Remove the need for vendor, which enables us to use npm link.

### PR DESCRIPTION
**Pull request by domoritz**
This will make it easier to develop vega/ vega-lite. We used npm link and bower link in voyager/polestar and had good experiences because you don't need to have another script running.

### CODE REVIEW

**Comment by domoritz** [comment]
I tried the deploy script and everything worked. I modified the deploy script to use my branch and not actually push and the gh-pages commit that was created worked.

**Comment by jheer** [comment]
Overall this looks good, though for the web app it is kind of odd to serve up files from a node_modules folder. Also, it looks like those (web hosted) node_modules will contain the entire packages, not just the build files...

**Comment by domoritz** [comment]
Yes, the disadvantage of this approach is that node_modules becomes huge.

**Comment by jheer** [comment]
Ugh.

**Comment by domoritz** [comment]
We could either use bower, only add the files that we actually want (git add in deploy.sh), or not use this approach at all and stick with vendor.sh.

**Comment by arvind** [comment]
Yeah, I'm not a fan of including the full `node_modules` in the deployment. Another alternative would be to add a simple npm script that mimics `npm link` but preserves vendor (e.g., `npm run ln: npm link vega && ln -s ...`).

**Comment by domoritz** [comment]
@arvind should we go with https://github.com/vega/vega-editor/commit/e9e1a46adde1fc066c4d3ff8d7b801c155671315? I can also implement the symlink version you proposed.

**Comment by arvind** [comment]
My preference would be to not expose "node_modules" in the deployed
version, as it feels very non-standard. I would be less pedantic if not for
the fact that we provide direct links to the editor's dependencies as part
of the starter code here: https://github.com/vega/vega/wiki/Runtime

We will also want to be a little careful with how we publish/change the
editor's dependencies. For example, removing the "vendor" directory will
break some of the examples the community has been developing recently on
bl.ocks.org.

However, if we felt that this PR was the best (or least worst?) of our
alternatives, I can go ahead and merge it.

Also, question, if this PR does not currently require bower, what is the
purpose of bower.json?

## -Arvind

Arvind Satyanarayan http://arvindsatya.com/

**Comment by domoritz** [comment]
Ups, forgot to remove bower.json.

I just noticed that the main reason why i did this, vega-lite, does not have a built version in npm. Is it standard to include it?

**Comment by domoritz** [comment]
Okay, the latest d3.cloud does not build for npm any more.

Options as discussed on slack:
- use only bower, without vendor (changes directories and breaks some people’s blocks but works otherwise)
- use vendor with bower instead of npm
- keep things as they are and use an old version of d3.cloud

**Comment by arvind** [comment]
This back-and-forth highlights why I liked `vendor` -- it abstracts away from the package manager du jour which, knowing the JS ecosystem, is highly likely to change!

**Comment by domoritz** [comment]
Need to reconsider my choices in life.

**Comment by arvind** [comment]
Bahahaha! My response to JavaScript: :cocktail:

**Comment by kanitw** [comment]
:cocktail: ><"

**Comment by kanitw** [comment]
Just realized that we enforce folder structure here, which I don’t like that much.  
But I’m probably too late in this conversation and it’s not much annoying. So I guess I'll have to live with that for now.

**Pull request closed without merging**
