### PR TITLE
toggle tooltip

### PR DESCRIPTION
**Pull request by starry97**
added toggle for tooltip #186.

### CODE REVIEW

**Comment by starry97** [comment]
We have too many buttons in the lower-right corner now. @domoritz Do you think we should move them somewhere else?

**Comment by nyurik** [comment]
It could be a popup with checkboxes - on mouse over, it would show an in-place popup with a list of checkboxes. This way clicking each checkbox would immediately change the state of the graph, and the popup wouldn't disappear until the mouse is moved away, allowing multiple checkboxes to be clicked one after another.

**Comment by domoritz** [comment]
A popup is one idea. Another one is a permanent bar at the bottom with all the options like

screen shot 2017-07-12 at 08 14 44

**Comment by nyurik** [comment]
Sure, but might get crowded

**Pull request merged**
