### PR TITLE
Use vega-datasets

### PR DESCRIPTION
**Pull request by domoritz**
Use https://github.com/vega/vega-datasets with git subtree

### CODE REVIEW

**Comment by arvind** [comment]
I would also add a `postvendor` node script to call `update-data.sh` to ensure everything is up to date for deployments.

**Comment by domoritz** [comment]
Done and also changed the branch for vega-data to gh-pages.

**Comment by kanitw** [comment]
Shall vega-data be named vega-example-data?

When i first saw the name, i thought its a module for running only the vega
data transform pipeline, which is a useful model for data processing in
voyager.

**Comment by arvind** [comment]
+1 to renaming. An alternative: vega-datasets.

**Comment by domoritz** [comment]
Renamed to vega-datasets

**Comment by kanitw** [comment]
Cool.  I like `vega-datasets`.   Practically it is `vega-example-datasets`, but that's too long so I think this is an ideal name.

**Comment by domoritz** [comment]
Any issues with this? I can push the latest changes from #10 to vega-data.

**Comment by arvind** [comment]
I was going to bring this up for us to go over quickly during the IDL meeting tomorrow, because it's unclear to me what issues this PR is resolving. As I understand it, we continue to have the issue of duplicating the data within each repository. It just so happens that the data is pulled from a central repository. 

And, by extracting the datasets to a common repository, we also add additional issues: (1) We have to maintain a log of changes to the datasets which, while not overly onerous, is an additional step; (2) Downstream repositories must now monitor and be responsive to changes in `vega-datasets`; (3) Each tool may use different/additional datasets to highlight their specific functionality but, because we use git subtree, this additional data is replicated across all repositories.

**Comment by domoritz** [comment]
Let's discuss this in the meeting tomorrow. I see the main advantage in that we use consistent example data in all our tools.

**Comment by kanitw** [comment]
One major motivation for this was that originally cars.json in vega-lite world (vega-lite editor, polestar, voyager) is a refactored version of one in the vega-editor although the dataset in both place has the same name.  Thus we cannot copy paste output vega spec and debug in vega-editor directly, which is annoying.

**Pull request merged**
