### PR TITLE
Permanent url

### PR DESCRIPTION
**Pull request by domoritz**
Shows a button that allows users to get a permanent url. 

We could also always update the url on render. I think that would be great since the user doesn't have to press a button any more. However, it could potentially be a bit annoying if the url changes all the time.

### CODE REVIEW

**Comment by arvind** [comment]
Yes, I agree that the URL should be updated automatically (and get rid of the button altogether). If we provide a button, I expect clicking it to perform a more active action (e.g., copy the URL into my clipboard a la GitHub, or show a modal dialog that allows me to copy the URL a la Google Maps). So, the current button feels a little broken to me. 

I also worry about adding permalink functionality that works only some of the time. For example, we can permalink configurations of the example specifications. But, we cannot link to a custom specification. This includes if a user selects an example, and then modifies it. Is it more frustrating to not have any permalink functionality exposed (but still parse params), or to have it only appear sometimes?

**Comment by domoritz** [comment]
> I also worry about adding permalink functionality that works only some of the time. For example, we can permalink configurations of the example specifications. But, we cannot link to a custom specification. 

I really don't know how well this scales but at least in my experiments it worked with http://localhost:8000/?mode=vega&spec=%7B%22width%22%3A300%2C%22height%22%3A240%2C%22data%22%3A%5B%7B%22name%22%3A%22table%22%2C%22values%22%3A%5B%7B%22category%22%3A%22A%22%2C%22position%22%3A0%2C%22value%22%3A0.1%7D%2C%7B%22category%22%3A%22A%22%2C%22position%22%3A1%2C%22value%22%3A0.6%7D%2C%7B%22category%22%3A%22A%22%2C%22position%22%3A2%2C%22value%22%3A0.9%7D%2C%7B%22category%22%3A%22A%22%2C%22position%22%3A3%2C%22value%22%3A0.4%7D%2C%7B%22category%22%3A%22B%22%2C%22position%22%3A0%2C%22value%22%3A0.7%7D%2C%7B%22category%22%3A%22B%22%2C%22position%22%3A1%2C%22value%22%3A0.2%7D%2C%7B%22category%22%3A%22B%22%2C%22position%22%3A2%2C%22value%22%3A1.1%7D%2C%7B%22category%22%3A%22B%22%2C%22position%22%3A3%2C%22value%22%3A0.8%7D%2C%7B%22category%22%3A%22C%22%2C%22position%22%3A0%2C%22value%22%3A0.6%7D%2C%7B%22category%22%3A%22C%22%2C%22position%22%3A1%2C%22value%22%3A0.1%7D%2C%7B%22category%22%3A%22C%22%2C%22position%22%3A2%2C%22value%22%3A0.2%7D%2C%7B%22category%22%3A%22C%22%2C%22position%22%3A3%2C%22value%22%3A0.7%7D%5D%7D%5D%2C%22scales%22%3A%5B%7B%22name%22%3A%22cat%22%2C%22type%22%3A%22ordinal%22%2C%22domain%22%3A%7B%22data%22%3A%22table%22%2C%22field%22%3A%22category%22%7D%2C%22range%22%3A%22height%22%2C%22padding%22%3A0.2%7D%2C%7B%22name%22%3A%22val%22%2C%22type%22%3A%22linear%22%2C%22domain%22%3A%7B%22data%22%3A%22table%22%2C%22field%22%3A%22value%22%7D%2C%22range%22%3A%22width%22%2C%22round%22%3Atrue%2C%22nice%22%3Atrue%7D%2C%7B%22name%22%3A%22color%22%2C%22type%22%3A%22ordinal%22%2C%22domain%22%3A%7B%22data%22%3A%22table%22%2C%22field%22%3A%22position%22%7D%2C%22range%22%3A%22category20%22%7D%5D%2C%22axes%22%3A%5B%7B%22type%22%3A%22y%22%2C%22scale%22%3A%22cat%22%2C%22tickSize%22%3A0%2C%22tickPadding%22%3A8%7D%2C%7B%22type%22%3A%22x%22%2C%22scale%22%3A%22val%22%7D%5D%2C%22marks%22%3A%5B%7B%22type%22%3A%22group%22%2C%22from%22%3A%7B%22data%22%3A%22table%22%2C%22transform%22%3A%5B%7B%22type%22%3A%22facet%22%2C%22groupby%22%3A%5B%22category%22%5D%7D%5D%7D%2C%22properties%22%3A%7B%22enter%22%3A%7B%22y%22%3A%7B%22scale%22%3A%22cat%22%2C%22field%22%3A%22key%22%7D%2C%22height%22%3A%7B%22scale%22%3A%22cat%22%2C%22band%22%3Atrue%7D%7D%7D%2C%22scales%22%3A%5B%7B%22name%22%3A%22pos%22%2C%22type%22%3A%22ordinal%22%2C%22range%22%3A%22height%22%2C%22domain%22%3A%7B%22field%22%3A%22position%22%7D%7D%5D%2C%22marks%22%3A%5B%7B%22name%22%3A%22bars%22%2C%22type%22%3A%22rect%22%2C%22properties%22%3A%7B%22enter%22%3A%7B%22y%22%3A%7B%22scale%22%3A%22pos%22%2C%22field%22%3A%22position%22%7D%2C%22height%22%3A%7B%22scale%22%3A%22pos%22%2C%22band%22%3Atrue%7D%2C%22x%22%3A%7B%22scale%22%3A%22val%22%2C%22field%22%3A%22value%22%7D%2C%22x2%22%3A%7B%22scale%22%3A%22val%22%2C%22value%22%3A0%7D%2C%22fill%22%3A%7B%22scale%22%3A%22color%22%2C%22field%22%3A%22position%22%7D%7D%7D%7D%2C%7B%22type%22%3A%22text%22%2C%22from%22%3A%7B%22mark%22%3A%22bars%22%7D%2C%22properties%22%3A%7B%22enter%22%3A%7B%22x%22%3A%7B%22field%22%3A%22x2%22%2C%22offset%22%3A-5%7D%2C%22y%22%3A%7B%22field%22%3A%22y%22%7D%2C%22dy%22%3A%7B%22field%22%3A%22height%22%2C%22mult%22%3A0.5%7D%2C%22fill%22%3A%7B%22value%22%3A%22white%22%7D%2C%22align%22%3A%7B%22value%22%3A%22right%22%7D%2C%22baseline%22%3A%7B%22value%22%3A%22middle%22%7D%2C%22text%22%3A%7B%22field%22%3A%22datum.value%22%7D%7D%7D%7D%5D%7D%5D%7D

I feel the best option is to always update the URL automatically but remove the permalink completely if the user writes a custom specification. How do you feel about that?

**Comment by domoritz** [comment]
Okay, it breaks down pretty quickly. You cannot paste this url:

[link](http://localhost:8000/?mode=vega&spec=%7B%22width%22%3A800%2C%22height%22%3A600%2C%22data%22%3A%5B%7B%22name%22%3A%22gapminder%22%2C%22url%22%3A%22data%2Fgapminder.json%22%7D%2C%7B%22name%22%3A%22clusters%22%2C%22values%22%3A%5B%7B%22id%22%3A0%2C%22name%22%3A%22South%20Asia%22%7D%2C%7B%22id%22%3A1%2C%22name%22%3A%22Europe%20%26%20Central%20Asia%22%7D%2C%7B%22id%22%3A2%2C%22name%22%3A%22Sub-Saharan%20Africa%22%7D%2C%7B%22id%22%3A3%2C%22name%22%3A%22America%22%7D%2C%7B%22id%22%3A4%2C%22name%22%3A%22East%20Asia%20%26%20Pacific%22%7D%2C%7B%22id%22%3A5%2C%22name%22%3A%22Middle%20East%20%26%20North%20Africa%22%7D%5D%7D%2C%7B%22name%22%3A%22country_timeline%22%2C%22source%22%3A%22gapminder%22%2C%22transform%22%3A%5B%7B%22type%22%3A%22filter%22%2C%22test%22%3A%22timeline%20%26%26%20datum.country%20%3D%3D%20timeline.country%22%7D%2C%7B%22type%22%3A%22sort%22%2C%22by%22%3A%22year%22%7D%5D%7D%2C%7B%22name%22%3A%22thisYear%22%2C%22source%22%3A%22gapminder%22%2C%22transform%22%3A%5B%7B%22type%22%3A%22filter%22%2C%22test%22%3A%22datum.year%20%3D%3D%20currentYear%22%7D%5D%7D%2C%7B%22name%22%3A%22prevYear%22%2C%22source%22%3A%22gapminder%22%2C%22transform%22%3A%5B%7B%22type%22%3A%22filter%22%2C%22test%22%3A%22datum.year%20%3D%3D%20currentYear-stepYear%22%7D%5D%7D%2C%7B%22name%22%3A%22nextYear%22%2C%22source%22%3A%22gapminder%22%2C%22transform%22%3A%5B%7B%22type%22%3A%22filter%22%2C%22test%22%3A%22datum.year%20%3D%3D%20currentYear%2BstepYear%22%7D%5D%7D%2C%7B%22name%22%3A%22countries%22%2C%22source%22%3A%22gapminder%22%2C%22transform%22%3A%5B%7B%22type%22%3A%22aggregate%22%2C%22groupby%22%3A%5B%22country%22%5D%2C%22summarize%22%3A%7B%22*%22%3A%22count%22%7D%7D%5D%7D%2C%7B%22name%22%3A%22interpolate%22%2C%22source%22%3A%22countries%22%2C%22transform%22%3A%5B%7B%22type%22%3A%22lookup%22%2C%22on%22%3A%22thisYear%22%2C%22onKey%22%3A%22country%22%2C%22keys%22%3A%5B%22country%22%5D%2C%22as%22%3A%5B%22this%22%5D%2C%22default%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22lookup%22%2C%22on%22%3A%22prevYear%22%2C%22onKey%22%3A%22country%22%2C%22keys%22%3A%5B%22country%22%5D%2C%22as%22%3A%5B%22prev%22%5D%2C%22default%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22lookup%22%2C%22on%22%3A%22nextYear%22%2C%22onKey%22%3A%22country%22%2C%22keys%22%3A%5B%22country%22%5D%2C%22as%22%3A%5B%22next%22%5D%2C%22default%22%3A%7B%7D%7D%2C%7B%22type%22%3A%22formula%22%2C%22field%22%3A%22target_fertility%22%2C%22expr%22%3A%22interYear%20%3E%20currentYear%20%3F%20datum.next.fertility%20%3A%20%28datum.prev.fertility%7C%7Cdatum.this.fertility%29%22%7D%2C%7B%22type%22%3A%22formula%22%2C%22field%22%3A%22target_life_expect%22%2C%22expr%22%3A%22interYear%20%3E%20currentYear%20%3F%20datum.next.life_expect%20%3A%20%28datum.prev.life_expect%7C%7Cdatum.this.life_expect%29%22%7D%2C%7B%22type%22%3A%22formula%22%2C%22field%22%3A%22inter_fertility%22%2C%22expr%22%3A%22interYear%3D%3D2000%20%3F%20datum.this.fertility%20%3A%20datum.this.fertility%20%2B%20%28datum.target_fertility-datum.this.fertility%29%20*%20abs%28interYear-datum.this.year%29%2F5%22%7D%2C%7B%22type%22%3A%22formula%22%2C%22field%22%3A%22inter_life_expect%22%2C%22expr%22%3A%22interYear%3D%3D2000%20%3F%20datum.this.life_expect%20%3A%20datum.this.life_expect%20%2B%20%28datum.target_life_expect-datum.this.life_expect%29%20*%20abs%28interYear-datum.this.year%29%2F5%22%7D%5D%7D%2C%7B%22name%22%3A%22trackCountries%22%2C%22modify%22%3A%5B%7B%22type%22%3A%22toggle%22%2C%22signal%22%3A%22active%22%2C%22field%22%3A%22active%22%7D%5D%7D%5D%2C%22signals%22%3A%5B%7B%22name%22%3A%22minYear%22%2C%22init%22%3A1955%7D%2C%7B%22name%22%3A%22maxYear%22%2C%22init%22%3A2005%7D%2C%7B%22name%22%3A%22stepYear%22%2C%22init%22%3A5%7D%2C%7B%22name%22%3A%22active%22%2C%22init%22%3A%7B%7D%2C%22streams%22%3A%5B%7B%22type%22%3A%22%40point%3Amousedown%2C%20%40point%3Atouchstart%22%2C%22expr%22%3A%22datum%22%7D%2C%7B%22type%22%3A%22window%3Amouseup%2C%20window%3Atouchend%22%2C%22expr%22%3A%22%7B%7D%22%7D%5D%7D%2C%7B%22name%22%3A%22isActive%22%2C%22expr%22%3A%22active.country%22%7D%2C%7B%22name%22%3A%22timeline%22%2C%22init%22%3A%7B%7D%2C%22streams%22%3A%5B%7B%22type%22%3A%22%40point%3Amouseover%22%2C%22expr%22%3A%22isActive%20%3F%20active%20%3A%20datum%22%7D%2C%7B%22type%22%3A%22%40point%3Amouseout%2C%20active%22%2C%22expr%22%3A%22active%22%7D%5D%7D%2C%7B%22name%22%3A%22tX%22%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22active.this.fertility%22%2C%22scale%22%3A%22x%22%7D%5D%7D%2C%7B%22name%22%3A%22tY%22%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22active.this.life_expect%22%2C%22scale%22%3A%22y%22%7D%5D%7D%2C%7B%22name%22%3A%22pX%22%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22active.prev.fertility%22%2C%22scale%22%3A%22x%22%7D%5D%7D%2C%7B%22name%22%3A%22pY%22%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22active.prev.life_expect%22%2C%22scale%22%3A%22y%22%7D%5D%7D%2C%7B%22name%22%3A%22nX%22%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22active.next.fertility%22%2C%22scale%22%3A%22x%22%7D%5D%7D%2C%7B%22name%22%3A%22nY%22%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22active.next.life_expect%22%2C%22scale%22%3A%22y%22%7D%5D%7D%2C%7B%22name%22%3A%22thisDist%22%2C%22init%22%3A0%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22sqrt%28pow%28eventX%28%29-tX%2C%202%29%20%2B%20pow%28eventY%28%29-tY%2C%202%29%29%22%7D%5D%7D%2C%7B%22name%22%3A%22prevDist%22%2C%22init%22%3A0%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22sqrt%28pow%28eventX%28%29-pX%2C%202%29%20%2B%20pow%28eventY%28%29-pY%2C%202%29%29%22%7D%5D%7D%2C%7B%22name%22%3A%22nextDist%22%2C%22init%22%3A0%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22sqrt%28pow%28eventX%28%29-nX%2C%202%29%20%2B%20pow%28eventY%28%29-nY%2C%202%29%29%22%7D%5D%7D%2C%7B%22name%22%3A%22prevScore%22%2C%22init%22%3A0%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22%28%28pX-tX%29%20*%20%28eventX%28%29-tX%29%20%2B%20%28pY-tY%29%20*%20%28eventY%28%29-tY%29%29%2FprevDist%20%7C%7C%20-999999%22%7D%5D%7D%2C%7B%22name%22%3A%22nextScore%22%2C%22init%22%3A0%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22%28%28nX-tX%29%20*%20%28eventX%28%29-tX%29%20%2B%20%28nY-tY%29%20*%20%28eventY%28%29-tY%29%29%2FnextDist%20%7C%7C%20-999999%22%7D%5D%7D%2C%7B%22name%22%3A%22interYear%22%2C%22init%22%3A1980%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22min%28maxYear%2C%20currentYear%2B5%2C%20max%28minYear%2C%20currentYear-5%2C%20prevScore%20%3E%20nextScore%20%3F%20%28currentYear%20-%202.5*prevScore%2Fsqrt%28pow%28pX-tX%2C%202%29%20%2B%20pow%28pY-tY%2C%202%29%29%29%20%3A%20%28currentYear%20%2B%202.5*nextScore%2Fsqrt%28pow%28nX-tX%2C%202%29%20%2B%20pow%28nY-tY%2C%202%29%29%29%29%29%22%7D%5D%7D%2C%7B%22name%22%3A%22currentYear%22%2C%22init%22%3A1980%2C%22streams%22%3A%5B%7B%22type%22%3A%22mousemove%5BisActive%5D%2C%20touchmove%5BisActive%5D%22%2C%22expr%22%3A%22min%28maxYear%2C%20max%28minYear%2C%20prevScore%20%3E%20nextScore%20%3F%20%28thisDist%20%3C%20prevDist%20%3F%20currentYear%20%3A%20currentYear-5%29%20%3A%20%28thisDist%20%3C%20nextDist%20%3F%20currentYear%20%3A%20currentYear%2B5%29%29%29%22%7D%5D%7D%5D%2C%22predicates%22%3A%5B%7B%22name%22%3A%22countryOfInterest%22%2C%22type%22%3A%22in%22%2C%22item%22%3A%7B%22arg%22%3A%22country%22%7D%2C%22data%22%3A%22trackCountries%22%2C%22field%22%3A%22active.country%22%7D%2C%7B%22name%22%3A%22activeCountry%22%2C%22type%22%3A%22%3D%3D%22%2C%22operands%22%3A%5B%7B%22arg%22%3A%22country%22%7D%2C%7B%22signal%22%3A%22timeline.country%22%7D%5D%7D%2C%7B%22name%22%3A%22show%22%2C%22type%22%3A%22or%22%2C%22operands%22%3A%5B%7B%22predicate%22%3A%22countryOfInterest%22%7D%2C%7B%22predicate%22%3A%22activeCountry%22%7D%5D%7D%5D%2C%22scales%22%3A%5B%7B%22name%22%3A%22x%22%2C%22type%22%3A%22linear%22%2C%22domain%22%3A%7B%22data%22%3A%22gapminder%22%2C%22field%22%3A%22fertility%22%7D%2C%22range%22%3A%22width%22%7D%2C%7B%22name%22%3A%22y%22%2C%22type%22%3A%22linear%22%2C%22domain%22%3A%7B%22data%22%3A%22gapminder%22%2C%22field%22%3A%22life_expect%22%7D%2C%22range%22%3A%22height%22%2C%22nice%22%3Atrue%2C%22zero%22%3Afalse%7D%2C%7B%22name%22%3A%22c%22%2C%22type%22%3A%22ordinal%22%2C%22domain%22%3A%7B%22data%22%3A%22gapminder%22%2C%22field%22%3A%22cluster%22%7D%2C%22range%22%3A%22category10%22%7D%2C%7B%22name%22%3A%22label%22%2C%22type%22%3A%22ordinal%22%2C%22domain%22%3A%7B%22data%22%3A%22clusters%22%2C%22field%22%3A%22id%22%7D%2C%22range%22%3A%7B%22data%22%3A%22clusters%22%2C%22field%22%3A%22name%22%7D%7D%5D%2C%22axes%22%3A%5B%7B%22title%22%3A%22Fertility%22%2C%22type%22%3A%22x%22%2C%22scale%22%3A%22x%22%2C%22grid%22%3Atrue%2C%22layer%22%3A%22back%22%2C%22ticks%22%3A5%7D%2C%7B%22title%22%3A%22Life%20Expectancy%22%2C%22type%22%3A%22y%22%2C%22scale%22%3A%22y%22%2C%22grid%22%3Atrue%2C%22layer%22%3A%22back%22%2C%22ticks%22%3A5%7D%5D%2C%22legends%22%3A%5B%7B%22fill%22%3A%22c%22%2C%22orient%22%3A%22right%22%2C%22properties%22%3A%7B%22labels%22%3A%7B%22text%22%3A%7B%22scale%22%3A%22label%22%2C%22field%22%3A%22data%22%7D%7D%7D%7D%5D%2C%22marks%22%3A%5B%7B%22type%22%3A%22text%22%2C%22properties%22%3A%7B%22update%22%3A%7B%22text%22%3A%7B%22signal%22%3A%22currentYear%22%7D%2C%22x%22%3A%7B%22value%22%3A300%7D%2C%22y%22%3A%7B%22value%22%3A300%7D%2C%22fill%22%3A%7B%22value%22%3A%22grey%22%7D%2C%22fillOpacity%22%3A%7B%22value%22%3A0.25%7D%2C%22fontSize%22%3A%7B%22value%22%3A100%7D%7D%7D%7D%2C%7B%22type%22%3A%22text%22%2C%22from%22%3A%7B%22data%22%3A%22country_timeline%22%7D%2C%22properties%22%3A%7B%22enter%22%3A%7B%22x%22%3A%7B%22scale%22%3A%22x%22%2C%22field%22%3A%22fertility%22%2C%22offset%22%3A5%7D%2C%22y%22%3A%7B%22scale%22%3A%22y%22%2C%22field%22%3A%22life_expect%22%7D%2C%22fill%22%3A%7B%22value%22%3A%22%23555%22%7D%2C%22fillOpacity%22%3A%7B%22value%22%3A0.6%7D%2C%22text%22%3A%7B%22field%22%3A%22year%22%7D%7D%7D%7D%2C%7B%22type%22%3A%22line%22%2C%22from%22%3A%7B%22data%22%3A%22country_timeline%22%7D%2C%22properties%22%3A%7B%22update%22%3A%7B%22x%22%3A%7B%22scale%22%3A%22x%22%2C%22field%22%3A%22fertility%22%7D%2C%22y%22%3A%7B%22scale%22%3A%22y%22%2C%22field%22%3A%22life_expect%22%7D%2C%22stroke%22%3A%7B%22value%22%3A%22%23bbb%22%7D%2C%22strokeWidth%22%3A%7B%22value%22%3A5%7D%2C%22strokeOpacity%22%3A%7B%22value%22%3A0.5%7D%7D%7D%7D%2C%7B%22type%22%3A%22text%22%2C%22from%22%3A%7B%22data%22%3A%22interpolate%22%7D%2C%22properties%22%3A%7B%22enter%22%3A%7B%22fill%22%3A%7B%22scale%22%3A%22c%22%2C%22field%22%3A%22this.cluster%22%7D%2C%22fontSize%22%3A%7B%22value%22%3A14%7D%2C%22fontWeight%22%3A%7B%22value%22%3A%22bold%22%7D%2C%22text%22%3A%7B%22field%22%3A%22country%22%7D%2C%22align%22%3A%7B%22value%22%3A%22center%22%7D%2C%22baseline%22%3A%7B%22value%22%3A%22bottom%22%7D%7D%2C%22update%22%3A%7B%22x%22%3A%7B%22scale%22%3A%22x%22%2C%22field%22%3A%22inter_fertility%22%7D%2C%22y%22%3A%7B%22scale%22%3A%22y%22%2C%22field%22%3A%22inter_life_expect%22%2C%22offset%22%3A-7%7D%2C%22fillOpacity%22%3A%7B%22rule%22%3A%5B%7B%22predicate%22%3A%7B%22name%22%3A%22show%22%2C%22country%22%3A%7B%22field%22%3A%22country%22%7D%7D%2C%22value%22%3A0.75%7D%2C%7B%22value%22%3A0%7D%5D%7D%7D%7D%7D%2C%7B%22name%22%3A%22point%22%2C%22type%22%3A%22symbol%22%2C%22from%22%3A%7B%22data%22%3A%22interpolate%22%7D%2C%22properties%22%3A%7B%22enter%22%3A%7B%22fill%22%3A%7B%22scale%22%3A%22c%22%2C%22field%22%3A%22this.cluster%22%7D%2C%22size%22%3A%7B%22value%22%3A150%7D%7D%2C%22update%22%3A%7B%22x%22%3A%7B%22scale%22%3A%22x%22%2C%22field%22%3A%22inter_fertility%22%7D%2C%22y%22%3A%7B%22scale%22%3A%22y%22%2C%22field%22%3A%22inter_life_expect%22%7D%2C%22fillOpacity%22%3A%7B%22rule%22%3A%5B%7B%22predicate%22%3A%7B%22name%22%3A%22show%22%2C%22country%22%3A%7B%22field%22%3A%22country%22%7D%7D%2C%22value%22%3A1%7D%2C%7B%22value%22%3A0.5%7D%5D%7D%7D%7D%7D%5D%7D)

But you can click on it ;-)

**Comment by arvind** [comment]
Yes, that doesn't scale. [Best practices](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) advocate for a URL length < 2000 characters. We ran into this issue earlier this summer which is why we added `postMessage` to the editor.

**Comment by domoritz** [comment]
@arvind What do you think about the behavior now?

**Comment by domoritz** [comment]
Removed the raw spec from the url and switch to custom when the user hits "parse".

**Pull request merged**
