### PR TITLE
Add a keyboard shortcut (F5) for Parse

### PR DESCRIPTION
**Pull request by arkadyan**
Wanted to propose this if there's interest. Not sure if this is the best shortcut, or how it's best implemented, but something along these lines seemed useful to me.

### CODE REVIEW

**Comment by kanitw** [comment]
I think F5 is not good for window users, because it's normally for refreshing the whole page.

**Comment by arkadyan** [comment]
@kanitw yeah, that's no good! Obviously I haven't used Windows in awhile… Any suggestions for something better? Maybe something like ⌘-⇧-P / ^-⇧-P? Though maybe a combo would require a different implementation?

**Comment by domoritz** [comment]
"shift return"

**Comment by kanitw** [comment]
I think @jhoffswell add some shortkey for interaction debugging too and probably have some input about this

**Comment by jhoffswell** [comment]
At this point, the debugging tools just use the arrow keys for navigating the timeline, no other shortcuts, though it might be a good idea to add one to switch between record (play) / replay (pause).

**Comment by domoritz** [comment]
Since we have a new editor, I'm closing this.

**Pull request closed without merging**
